---
wordpress:
  service:
    type: ClusterIP
  wordpressUsername: runejuhl
  wordpressPassword: "aBadPassword"
  existingSecret: ""
  wordpressEmail: rune.juhl@atea.dk
  wordpressFirstName: Rune
  wordpressLastName: Juhl
  wordpressBlogName: |
    My special blog!
  replicaCount: 1
  ingress:
    enabled: true
    hostname: wordpress.local
    path: /
    annotations:
      kubernetes.io/ingress.class: "traefik"
